spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core_service
    username: postgres
    password: ali.1381
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082